USE OTC_PLATFORM
GO

IF EXISTS(SELECT NAME FROM sys.objects WHERE name = 'SP_CREATE_MODEL_U' AND type='P')
BEGIN
	DROP PROCEDURE SP_CREATE_MODEL_U
END
GO

CREATE PROCEDURE SP_CREATE_MODEL_U
(	
	@TABLE VARCHAR(80)
)
AS
BEGIN

	DECLARE @NAME VARCHAR(80) = 'SP' + SUBSTRING(@TABLE,3, LEN(@TABLE)) +'_U'
	DECLARE @SQL NVARCHAR(MAX)
	DECLARE @BR CHAR(2) = CHAR(13)
	DECLARE @TAB CHAR(2) = CHAR(9)

	DECLARE @ID							int
	DECLARE @COLUMN_NAME				sysname
	DECLARE @DATA_TYPE					nvarchar(256)
	DECLARE @CHARACTER_MAXIMUM_LENGTH	int
	DECLARE @NUMERIC_PRECISION			tinyint
	DECLARE @NUMERIC_SCALE				int
	DECLARE @IS_NULLABLE				varchar(3)
	DECLARE @PK_NAME					varchar(100)
		
	SET NOCOUNT ON

	SELECT 
		@PK_NAME = B.COLUMN_NAME
		--B.TABLE_CATALOG,
		--B.TABLE_SCHEMA,
		--B.TABLE_NAME,
		--B.COLUMN_NAME
	FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS AS A

	INNER JOIN INFORMATION_SCHEMA.KEY_COLUMN_USAGE B
	ON A.CONSTRAINT_TYPE = 'PRIMARY KEY' 
	AND A.CONSTRAINT_NAME = B.CONSTRAINT_NAME

	WHERE B.TABLE_NAME = @TABLE

	CREATE TABLE #TB_TEMP
	(
		ID							int IDENTITY(1,1) PRIMARY KEY,
		COLUMN_NAME					sysname,
		DATA_TYPE					nvarchar(256),
		CHARACTER_MAXIMUM_LENGTH	int,
		NUMERIC_PRECISION			tinyint,
		NUMERIC_SCALE				int,
		IS_NULLABLE					varchar(3),
		FOR_SIGNATURE				bit,
		FOR_BODY					bit,
		FOR_PARAM					bit
	)

	INSERT INTO #TB_TEMP
	SELECT
		COLUMN_NAME,
		DATA_TYPE,
		CHARACTER_MAXIMUM_LENGTH,
		NUMERIC_PRECISION,
		NUMERIC_SCALE,
		IS_NULLABLE,
		0,
		0,
		0
	FROM INFORMATION_SCHEMA.COLUMNS WHERE TABLE_NAME= @TABLE	

	-- Set the database
	SET @SQL = ' USE ' + DB_NAME() + @BR
	SET @SQL+= 'GO' + @BR + @BR
	
	-- Delete the previous procedure version
	SET @SQL+= 'IF EXISTS(SELECT NAME FROM sys.objects WHERE name = ''' + @NAME + ''' AND type=''P'')' + @BR
	SET @SQL+= 'BEGIN' + @BR
		SET @SQL+= @TAB + 'DROP PROCEDURE '+ @NAME +'' + @BR
	SET @SQL+= 'END' + @BR
	SET @SQL+= 'GO' + @BR + @BR
	
	-- Create procedure statement
	SET @SQL+='CREATE PROCEDURE '+ @NAME +''  + @BR
	SET @SQL+='(' + @BR

	WHILE(1=1)
	BEGIN

		SET @ID = 0;

		SELECT @ID = (SELECT MIN(ID) FROM #TB_TEMP WHERE FOR_SIGNATURE = 0)
		
		IF(@ID=NULL OR @ID IS NULL)
		BEGIN
			BREAK
		END

		DECLARE @LAST_ROW BIT =1

		IF EXISTS(SELECT ID FROM #TB_TEMP WHERE ID> @ID AND FOR_SIGNATURE = 0)
		BEGIN
			SET @LAST_ROW=0
		END

		SELECT 
			@COLUMN_NAME				= COLUMN_NAME,
			@DATA_TYPE					= DATA_TYPE,
			@CHARACTER_MAXIMUM_LENGTH	= CHARACTER_MAXIMUM_LENGTH,
			@NUMERIC_PRECISION			= NUMERIC_PRECISION,
			@NUMERIC_SCALE				= NUMERIC_SCALE
		FROM #TB_TEMP WHERE ID = @ID

		IF(@CHARACTER_MAXIMUM_LENGTH !=NULL OR @CHARACTER_MAXIMUM_LENGTH IS NOT NULL)
		BEGIN
			SET @SQL+= @TAB + '@P_'+ @COLUMN_NAME + @TAB + @DATA_TYPE + '(' + CONVERT(VARCHAR,@CHARACTER_MAXIMUM_LENGTH) + ')'
		END
		ELSE
		BEGIN

			IF(@NUMERIC_PRECISION IS NOT NULL AND @NUMERIC_SCALE IS NOT NULL AND @NUMERIC_SCALE>0)
			BEGIN
				SET @SQL+= @TAB + '@P_'+ @COLUMN_NAME + @TAB + @DATA_TYPE + '(' + CONVERT(VARCHAR,@NUMERIC_PRECISION) + ',' + CONVERT(VARCHAR,@NUMERIC_SCALE) +')'
			END
			ELSE
			BEGIN
				SET @SQL+= @TAB + '@P_'+ @COLUMN_NAME + @TAB + @DATA_TYPE
			END 
		END
		
		IF(@LAST_ROW=0)
		BEGIN
			SET @SQL+= ',' + @BR
		END
		ELSE
		BEGIN
			SET @SQL+= @BR
		END

		UPDATE #TB_TEMP SET FOR_SIGNATURE =1 WHERE ID = @ID
	END
	SET @SQL+=')' + @BR
	
	SET @SQL+='AS' + @BR
	SET @SQL+='BEGIN' + @BR + @BR

	SET @SQL+=@TAB + 'UPDATE ' + @TABLE + ' SET' + @BR

	WHILE(1=1)
	BEGIN

		SET @ID = 0;

		SELECT @ID = (SELECT MIN(ID) FROM #TB_TEMP WHERE FOR_BODY=0)
		
		IF(@ID=NULL OR @ID IS NULL)
		BEGIN
			BREAK
		END	

		SET @LAST_ROW  =1

		IF EXISTS(SELECT ID FROM #TB_TEMP WHERE ID> @ID AND FOR_BODY = 0)
		BEGIN
			SET @LAST_ROW=0
		END

		SELECT 
			@COLUMN_NAME = COLUMN_NAME,
			@DATA_TYPE   = DATA_TYPE
		FROM #TB_TEMP WHERE ID = @ID

		IF(@COLUMN_NAME = @PK_NAME)
		BEGIN
			UPDATE #TB_TEMP SET FOR_BODY=1 WHERE ID = @ID
		END
		ELSE
		BEGIN

			IF(@LAST_ROW=0)
			BEGIN
				SET @SQL+= @TAB + @TAB + @COLUMN_NAME + ' = ' + '@P_' + @COLUMN_NAME + ',' + @BR 
			END
			ELSE
			BEGIN
				SET @SQL+= @TAB + @TAB + @COLUMN_NAME + ' = ' + '@P_' + @COLUMN_NAME + @BR
			END
		
			UPDATE #TB_TEMP SET FOR_BODY=1 WHERE ID = @ID

		END
	END
	SET @SQL+=@TAB + 'WHERE ' + @PK_NAME + ' = @P_' + @PK_NAME + @BR + @BR
		
	
	SET @SQL+='END' + @BR
	SET @SQL+='GO' + @BR + @BR

	-- Grant execute statement
	SET @SQL+='GRANT EXECUTE ON '+ @NAME +' TO PUBLIC' + @BR
	SET @SQL+='GO' + @BR

	PRINT @SQL
	DROP TABLE #TB_TEMP
	   	     
	END
	GO

GRANT EXECUTE ON SP_CREATE_MODEL_U TO PUBLIC
GO